/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/MFnFUSkOGoP
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'
import { Arimo } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

arimo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { Card } from '@/components/ui/card'
import {
  DropdownMenu,
  DropdownMenuCheckboxItem,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuLabel,
  DropdownMenuSeparator,
  DropdownMenuTrigger,
} from '@/components/ui/dropdown-menu'
import { Input } from '@/components/ui/input'
import {
  Pagination,
  PaginationContent,
  PaginationItem,
} from '@/components/ui/pagination'
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from '@/components/ui/table'
import { SVGProps } from 'react'
import { JSX } from 'react/jsx-runtime'

export function Hook() {
  return (
    <div className='flex flex-col gap-6 p-6 md:p-8'>
      <div className='flex items-center justify-between'>
        <h1 className='text-2xl font-bold'>Webhook Management</h1>
        <Button>Create Webhook</Button>
      </div>
      <div className='flex flex-col md:flex-row items-center gap-4'>
        <Input
          type='search'
          placeholder='Search webhooks...'
          className='flex-1'
        />
        <div className='flex flex-col md:flex-row items-center gap-4'>
          <DropdownMenu>
            <DropdownMenuTrigger asChild>
              <Button variant='outline'>
                <FilterIcon className='h-4 w-4 mr-2' />
                Filter
              </Button>
            </DropdownMenuTrigger>
            <DropdownMenuContent align='end' className='w-56'>
              <DropdownMenuLabel>Filter by Status</DropdownMenuLabel>
              <DropdownMenuSeparator />
              <DropdownMenuCheckboxItem>Enabled</DropdownMenuCheckboxItem>
              <DropdownMenuCheckboxItem>Disabled</DropdownMenuCheckboxItem>
            </DropdownMenuContent>
          </DropdownMenu>
          <DropdownMenu>
            <DropdownMenuTrigger asChild>
              <Button variant='outline'>
                <FilterIcon className='h-4 w-4 mr-2' />
                Filter by App
              </Button>
            </DropdownMenuTrigger>
            <DropdownMenuContent align='end' className='w-56'>
              <DropdownMenuLabel>Filter by App</DropdownMenuLabel>
              <DropdownMenuSeparator />
              <DropdownMenuCheckboxItem>Feishu</DropdownMenuCheckboxItem>
              <DropdownMenuCheckboxItem>Dingtalk</DropdownMenuCheckboxItem>
              <DropdownMenuCheckboxItem>WeChat</DropdownMenuCheckboxItem>
              <DropdownMenuCheckboxItem>Slack</DropdownMenuCheckboxItem>
              <DropdownMenuCheckboxItem>Discord</DropdownMenuCheckboxItem>
            </DropdownMenuContent>
          </DropdownMenu>
        </div>
      </div>
      <div className='overflow-auto border rounded-lg md:hidden'>
        <div className='grid gap-4 p-4'>
          <Card>
            <div className='flex items-center gap-2'>
              <FeatherIcon className='h-5 w-5' />
              <div>Feishu</div>
            </div>
            <div>https://example.com/feishu</div>
            <div>
              <Badge variant='secondary'>Enabled</Badge>
            </div>
            <div>2 hours ago</div>
            <div>
              <DropdownMenu>
                <DropdownMenuTrigger asChild>
                  <Button size='icon' variant='ghost'>
                    <MoveHorizontalIcon className='h-4 w-4' />
                    <span className='sr-only'>More actions</span>
                  </Button>
                </DropdownMenuTrigger>
                <DropdownMenuContent align='end'>
                  <DropdownMenuItem>Edit</DropdownMenuItem>
                  <DropdownMenuItem>Disable</DropdownMenuItem>
                  <DropdownMenuItem>Delete</DropdownMenuItem>
                </DropdownMenuContent>
              </DropdownMenu>
            </div>
          </Card>
          <Card>
            <div className='flex items-center gap-2'>
              <PhoneCallIcon className='h-5 w-5' />
              <div>Dingtalk</div>
            </div>
            <div>https://example.com/dingtalk</div>
            <div>
              <Badge variant='outline'>Disabled</Badge>
            </div>
            <div>3 days ago</div>
            <div>
              <DropdownMenu>
                <DropdownMenuTrigger asChild>
                  <Button size='icon' variant='ghost'>
                    <MoveHorizontalIcon className='h-4 w-4' />
                    <span className='sr-only'>More actions</span>
                  </Button>
                </DropdownMenuTrigger>
                <DropdownMenuContent align='end'>
                  <DropdownMenuItem>Edit</DropdownMenuItem>
                  <DropdownMenuItem>Enable</DropdownMenuItem>
                  <DropdownMenuItem>Delete</DropdownMenuItem>
                </DropdownMenuContent>
              </DropdownMenu>
            </div>
          </Card>
          <Card>
            <div className='flex items-center gap-2'>
              <PhoneIcon className='h-5 w-5' />
              <div>WeChat</div>
            </div>
            <div>https://example.com/wechat</div>
            <div>
              <Badge variant='secondary'>Enabled</Badge>
            </div>
            <div>1 week ago</div>
            <div>
              <DropdownMenu>
                <DropdownMenuTrigger asChild>
                  <Button size='icon' variant='ghost'>
                    <MoveHorizontalIcon className='h-4 w-4' />
                    <span className='sr-only'>More actions</span>
                  </Button>
                </DropdownMenuTrigger>
                <DropdownMenuContent align='end'>
                  <DropdownMenuItem>Edit</DropdownMenuItem>
                  <DropdownMenuItem>Disable</DropdownMenuItem>
                  <DropdownMenuItem>Delete</DropdownMenuItem>
                </DropdownMenuContent>
              </DropdownMenu>
            </div>
          </Card>
          <Card>
            <div className='flex items-center gap-2'>
              <SlackIcon className='h-5 w-5' />
              <div>Slack</div>
            </div>
            <div>https://example.com/slack</div>
            <div>
              <Badge variant='outline'>Disabled</Badge>
            </div>
            <div>2 weeks ago</div>
            <div>
              <DropdownMenu>
                <DropdownMenuTrigger asChild>
                  <Button size='icon' variant='ghost'>
                    <MoveHorizontalIcon className='h-4 w-4' />
                    <span className='sr-only'>More actions</span>
                  </Button>
                </DropdownMenuTrigger>
                <DropdownMenuContent align='end'>
                  <DropdownMenuItem>Edit</DropdownMenuItem>
                  <DropdownMenuItem>Enable</DropdownMenuItem>
                  <DropdownMenuItem>Delete</DropdownMenuItem>
                </DropdownMenuContent>
              </DropdownMenu>
            </div>
          </Card>
          <Card>
            <div className='flex items-center gap-2'>
              <DiscIcon className='h-5 w-5' />
              <div>Discord</div>
            </div>
            <div>https://example.com/discord</div>
            <div>
              <Badge variant='secondary'>Enabled</Badge>
            </div>
            <div>1 month ago</div>
            <div>
              <DropdownMenu>
                <DropdownMenuTrigger asChild>
                  <Button size='icon' variant='ghost'>
                    <MoveHorizontalIcon className='h-4 w-4' />
                    <span className='sr-only'>More actions</span>
                  </Button>
                </DropdownMenuTrigger>
                <DropdownMenuContent align='end'>
                  <DropdownMenuItem>Edit</DropdownMenuItem>
                  <DropdownMenuItem>Disable</DropdownMenuItem>
                  <DropdownMenuItem>Delete</DropdownMenuItem>
                </DropdownMenuContent>
              </DropdownMenu>
            </div>
          </Card>
        </div>
      </div>
      <div className='overflow-auto border rounded-lg hidden md:block'>
        <Table>
          <TableHeader className='bg-muted'>
            <TableRow>
              <TableHead>Service</TableHead>
              <TableHead>URL</TableHead>
              <TableHead>Status</TableHead>
              <TableHead>Last Triggered</TableHead>
              <TableHead>Actions</TableHead>
            </TableRow>
          </TableHeader>
          <TableBody>
            <TableRow>
              <TableCell>
                <div className='flex items-center gap-2'>
                  <FeatherIcon className='h-5 w-5' />
                  Feishu
                </div>
              </TableCell>
              <TableCell>https://example.com/feishu</TableCell>
              <TableCell>
                <Badge variant='secondary'>Enabled</Badge>
              </TableCell>
              <TableCell>2 hours ago</TableCell>
              <TableCell>
                <DropdownMenu>
                  <DropdownMenuTrigger asChild>
                    <Button size='icon' variant='ghost'>
                      <MoveHorizontalIcon className='h-4 w-4' />
                      <span className='sr-only'>More actions</span>
                    </Button>
                  </DropdownMenuTrigger>
                  <DropdownMenuContent align='end'>
                    <DropdownMenuItem>Edit</DropdownMenuItem>
                    <DropdownMenuItem>Disable</DropdownMenuItem>
                    <DropdownMenuItem>Delete</DropdownMenuItem>
                  </DropdownMenuContent>
                </DropdownMenu>
              </TableCell>
            </TableRow>
            <TableRow>
              <TableCell>
                <div className='flex items-center gap-2'>
                  <PhoneCallIcon className='h-5 w-5' />
                  Dingtalk
                </div>
              </TableCell>
              <TableCell>https://example.com/dingtalk</TableCell>
              <TableCell>
                <Badge variant='outline'>Disabled</Badge>
              </TableCell>
              <TableCell>3 days ago</TableCell>
              <TableCell>
                <DropdownMenu>
                  <DropdownMenuTrigger asChild>
                    <Button size='icon' variant='ghost'>
                      <MoveHorizontalIcon className='h-4 w-4' />
                      <span className='sr-only'>More actions</span>
                    </Button>
                  </DropdownMenuTrigger>
                  <DropdownMenuContent align='end'>
                    <DropdownMenuItem>Edit</DropdownMenuItem>
                    <DropdownMenuItem>Enable</DropdownMenuItem>
                    <DropdownMenuItem>Delete</DropdownMenuItem>
                  </DropdownMenuContent>
                </DropdownMenu>
              </TableCell>
            </TableRow>
            <TableRow>
              <TableCell>
                <div className='flex items-center gap-2'>
                  <PhoneIcon className='h-5 w-5' />
                  WeChat
                </div>
              </TableCell>
              <TableCell>https://example.com/wechat</TableCell>
              <TableCell>
                <Badge variant='secondary'>Enabled</Badge>
              </TableCell>
              <TableCell>1 week ago</TableCell>
              <TableCell>
                <DropdownMenu>
                  <DropdownMenuTrigger asChild>
                    <Button size='icon' variant='ghost'>
                      <MoveHorizontalIcon className='h-4 w-4' />
                      <span className='sr-only'>More actions</span>
                    </Button>
                  </DropdownMenuTrigger>
                  <DropdownMenuContent align='end'>
                    <DropdownMenuItem>Edit</DropdownMenuItem>
                    <DropdownMenuItem>Disable</DropdownMenuItem>
                    <DropdownMenuItem>Delete</DropdownMenuItem>
                  </DropdownMenuContent>
                </DropdownMenu>
              </TableCell>
            </TableRow>
            <TableRow>
              <TableCell>
                <div className='flex items-center gap-2'>
                  <SlackIcon className='h-5 w-5' />
                  Slack
                </div>
              </TableCell>
              <TableCell>https://example.com/slack</TableCell>
              <TableCell>
                <Badge variant='outline'>Disabled</Badge>
              </TableCell>
              <TableCell>2 weeks ago</TableCell>
              <TableCell>
                <DropdownMenu>
                  <DropdownMenuTrigger asChild>
                    <Button size='icon' variant='ghost'>
                      <MoveHorizontalIcon className='h-4 w-4' />
                      <span className='sr-only'>More actions</span>
                    </Button>
                  </DropdownMenuTrigger>
                  <DropdownMenuContent align='end'>
                    <DropdownMenuItem>Edit</DropdownMenuItem>
                    <DropdownMenuItem>Enable</DropdownMenuItem>
                    <DropdownMenuItem>Delete</DropdownMenuItem>
                  </DropdownMenuContent>
                </DropdownMenu>
              </TableCell>
            </TableRow>
            <TableRow>
              <TableCell>
                <div className='flex items-center gap-2'>
                  <DiscIcon className='h-5 w-5' />
                  Discord
                </div>
              </TableCell>
              <TableCell>https://example.com/discord</TableCell>
              <TableCell>
                <Badge variant='secondary'>Enabled</Badge>
              </TableCell>
              <TableCell>1 month ago</TableCell>
              <TableCell>
                <DropdownMenu>
                  <DropdownMenuTrigger asChild>
                    <Button size='icon' variant='ghost'>
                      <MoveHorizontalIcon className='h-4 w-4' />
                      <span className='sr-only'>More actions</span>
                    </Button>
                  </DropdownMenuTrigger>
                  <DropdownMenuContent align='end'>
                    <DropdownMenuItem>Edit</DropdownMenuItem>
                    <DropdownMenuItem>Disable</DropdownMenuItem>
                    <DropdownMenuItem>Delete</DropdownMenuItem>
                  </DropdownMenuContent>
                </DropdownMenu>
              </TableCell>
            </TableRow>
          </TableBody>
        </Table>
      </div>
      <Pagination className='justify-end'>
        <PaginationContent>
          <PaginationItem>
            <Button size='icon' variant='outline'>
              <ChevronLeftIcon className='h-4 w-4' />
              <span className='sr-only'>Previous</span>
            </Button>
          </PaginationItem>
          <PaginationItem>
            <Button size='icon' variant='outline'>
              <ChevronRightIcon className='h-4 w-4' />
              <span className='sr-only'>Next</span>
            </Button>
          </PaginationItem>
        </PaginationContent>
      </Pagination>
    </div>
  )
}

function ChevronLeftIcon(
  props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>
) {
  return (
    <svg
      {...props}
      xmlns='http://www.w3.org/2000/svg'
      width='24'
      height='24'
      viewBox='0 0 24 24'
      fill='none'
      stroke='currentColor'
      strokeWidth='2'
      strokeLinecap='round'
      strokeLinejoin='round'
    >
      <path d='m15 18-6-6 6-6' />
    </svg>
  )
}

function ChevronRightIcon(
  props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>
) {
  return (
    <svg
      {...props}
      xmlns='http://www.w3.org/2000/svg'
      width='24'
      height='24'
      viewBox='0 0 24 24'
      fill='none'
      stroke='currentColor'
      strokeWidth='2'
      strokeLinecap='round'
      strokeLinejoin='round'
    >
      <path d='m9 18 6-6-6-6' />
    </svg>
  )
}

function DiscIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns='http://www.w3.org/2000/svg'
      width='24'
      height='24'
      viewBox='0 0 24 24'
      fill='none'
      stroke='currentColor'
      strokeWidth='2'
      strokeLinecap='round'
      strokeLinejoin='round'
    >
      <circle cx='12' cy='12' r='10' />
      <circle cx='12' cy='12' r='2' />
    </svg>
  )
}

function FeatherIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns='http://www.w3.org/2000/svg'
      width='24'
      height='24'
      viewBox='0 0 24 24'
      fill='none'
      stroke='currentColor'
      strokeWidth='2'
      strokeLinecap='round'
      strokeLinejoin='round'
    >
      <path d='M12.67 19a2 2 0 0 0 1.416-.588l6.154-6.172a6 6 0 0 0-8.49-8.49L5.586 9.914A2 2 0 0 0 5 11.328V18a1 1 0 0 0 1 1z' />
      <path d='M16 8 2 22' />
      <path d='M17.5 15H9' />
    </svg>
  )
}

function FilterIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns='http://www.w3.org/2000/svg'
      width='24'
      height='24'
      viewBox='0 0 24 24'
      fill='none'
      stroke='currentColor'
      strokeWidth='2'
      strokeLinecap='round'
      strokeLinejoin='round'
    >
      <polygon points='22 3 2 3 10 12.46 10 19 14 21 14 12.46 22 3' />
    </svg>
  )
}

function MoveHorizontalIcon(
  props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>
) {
  return (
    <svg
      {...props}
      xmlns='http://www.w3.org/2000/svg'
      width='24'
      height='24'
      viewBox='0 0 24 24'
      fill='none'
      stroke='currentColor'
      strokeWidth='2'
      strokeLinecap='round'
      strokeLinejoin='round'
    >
      <polyline points='18 8 22 12 18 16' />
      <polyline points='6 8 2 12 6 16' />
      <line x1='2' x2='22' y1='12' y2='12' />
    </svg>
  )
}

function PhoneCallIcon(
  props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>
) {
  return (
    <svg
      {...props}
      xmlns='http://www.w3.org/2000/svg'
      width='24'
      height='24'
      viewBox='0 0 24 24'
      fill='none'
      stroke='currentColor'
      strokeWidth='2'
      strokeLinecap='round'
      strokeLinejoin='round'
    >
      <path d='M22 16.92v3a2 2 0 0 1-2.18 2 19.79 19.79 0 0 1-8.63-3.07 19.5 19.5 0 0 1-6-6 19.79 19.79 0 0 1-3.07-8.67A2 2 0 0 1 4.11 2h3a2 2 0 0 1 2 1.72 12.84 12.84 0 0 0 .7 2.81 2 2 0 0 1-.45 2.11L8.09 9.91a16 16 0 0 0 6 6l1.27-1.27a2 2 0 0 1 2.11-.45 12.84 12.84 0 0 0 2.81.7A2 2 0 0 1 22 16.92z' />
      <path d='M14.05 2a9 9 0 0 1 8 7.94' />
      <path d='M14.05 6A5 5 0 0 1 18 10' />
    </svg>
  )
}

function PhoneIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns='http://www.w3.org/2000/svg'
      width='24'
      height='24'
      viewBox='0 0 24 24'
      fill='none'
      stroke='currentColor'
      strokeWidth='2'
      strokeLinecap='round'
      strokeLinejoin='round'
    >
      <path d='M22 16.92v3a2 2 0 0 1-2.18 2 19.79 19.79 0 0 1-8.63-3.07 19.5 19.5 0 0 1-6-6 19.79 19.79 0 0 1-3.07-8.67A2 2 0 0 1 4.11 2h3a2 2 0 0 1 2 1.72 12.84 12.84 0 0 0 .7 2.81 2 2 0 0 1-.45 2.11L8.09 9.91a16 16 0 0 0 6 6l1.27-1.27a2 2 0 0 1 2.11-.45 12.84 12.84 0 0 0 2.81.7A2 2 0 0 1 22 16.92z' />
    </svg>
  )
}

function SlackIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns='http://www.w3.org/2000/svg'
      width='24'
      height='24'
      viewBox='0 0 24 24'
      fill='none'
      stroke='currentColor'
      strokeWidth='2'
      strokeLinecap='round'
      strokeLinejoin='round'
    >
      <rect width='3' height='8' x='13' y='2' rx='1.5' />
      <path d='M19 8.5V10h1.5A1.5 1.5 0 1 0 19 8.5' />
      <rect width='3' height='8' x='8' y='14' rx='1.5' />
      <path d='M5 15.5V14H3.5A1.5 1.5 0 1 0 5 15.5' />
      <rect width='8' height='3' x='14' y='13' rx='1.5' />
      <path d='M15.5 19H14v1.5a1.5 1.5 0 1 0 1.5-1.5' />
      <rect width='8' height='3' x='2' y='8' rx='1.5' />
      <path d='M8.5 5H10V3.5A1.5 1.5 0 1 0 8.5 5' />
    </svg>
  )
}
